"""deqcert -- a dequantization certifier for parameterised quantum circuit encoders.

Given a description of a PQC feature encoder, decide whether its readout can be
reproduced by a comparably cheap classical model, and if so return that model
explicitly.

The verdict is settled by two quantities: the dimension of the circuit's
dynamical Lie algebra, and the frequency support generated by the data encoding.
Three outcomes are possible.

  frequency escape  the encoding re-uploads data at a trainable scale, so the
                    readout leaves any fixed finite basis
  algebra escape    the readout exhausts the space a bounded algebra allows;
                    an entanglement reading indicates whether that is costly
  dequantizable     an explicit classical surrogate is returned, fitted from
                    circuit evaluations alone and accepted only at a round-off
                    residual, together with its evaluation cost

An escape verdict means the circuit is not reproducible by the surrogate this
tool constructs. It never means a quantum advantage has been demonstrated.

Quick start
-----------
    >>> from deqcert import certify, print_report, EXAMPLES
    >>> print_report(certify(EXAMPLES["hqz_base"]()))

or from the command line::

    deqcert hqz_base
    deqcert --selftest
"""

from .certifier import (
    EncoderSpec,
    Report,
    EXAMPLES,
    certify,
    print_report,
    extract_surrogate,
    dla_dimension,
    frequency_axis,
    effective_dimension,
    mean_entanglement,
    readout_support,
    statevector,
    simulate,
)

__all__ = [
    "EncoderSpec",
    "Report",
    "EXAMPLES",
    "certify",
    "print_report",
    "extract_surrogate",
    "dla_dimension",
    "frequency_axis",
    "effective_dimension",
    "mean_entanglement",
    "readout_support",
    "statevector",
    "simulate",
    "from_qiskit",
]

__version__ = "0.1.0"


def from_qiskit(*args, **kwargs):
    """Build an :class:`EncoderSpec` from a Qiskit ``QuantumCircuit``.

    Requires the optional dependency: ``pip install deqcert[qiskit]``.
    """
    try:
        from .qiskit_import import from_qiskit as _f
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "from_qiskit requires qiskit. Install it with: pip install deqcert[qiskit]"
        ) from exc
    return _f(*args, **kwargs)
